// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol EdgeNetworkStub: Sendable {
    func initializeZone(
      request: InitializeZoneRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.InitializeZoneResponse

    func listZones(
      request: ListZonesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.ListZonesResponse

    func getZone(
      request: GetZoneRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.Zone

    func listNetworks(
      request: ListNetworksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.ListNetworksResponse

    func getNetwork(
      request: GetNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.Network

    func diagnoseNetwork(
      request: DiagnoseNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.DiagnoseNetworkResponse

    func createNetwork(
      request: CreateNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteNetwork(
      request: DeleteNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listSubnets(
      request: ListSubnetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.ListSubnetsResponse

    func getSubnet(
      request: GetSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.Subnet

    func createSubnet(
      request: CreateSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateSubnet(
      request: UpdateSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteSubnet(
      request: DeleteSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listInterconnects(
      request: ListInterconnectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.ListInterconnectsResponse

    func getInterconnect(
      request: GetInterconnectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.Interconnect

    func diagnoseInterconnect(
      request: DiagnoseInterconnectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.DiagnoseInterconnectResponse

    func listInterconnectAttachments(
      request: ListInterconnectAttachmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.ListInterconnectAttachmentsResponse

    func getInterconnectAttachment(
      request: GetInterconnectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.InterconnectAttachment

    func createInterconnectAttachment(
      request: CreateInterconnectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteInterconnectAttachment(
      request: DeleteInterconnectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRouters(
      request: ListRoutersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.ListRoutersResponse

    func getRouter(
      request: GetRouterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.Router

    func diagnoseRouter(
      request: DiagnoseRouterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeNetworkV1.DiagnoseRouterResponse

    func createRouter(
      request: CreateRouterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateRouter(
      request: UpdateRouterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRouter(
      request: DeleteRouterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
