// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

/// EdgeNetwork API provides managed, highly available cloud dynamic network
/// configuration service to the GEC customer to enable edge application and
/// network function solutions. This allows the customers to easily define and
/// configure the network setup and property to meet the workload requirement.
///
/// @Snippet(path: "EdgeNetworkQuickstart")
public class EdgeNetworkClient: Clients.EdgeNetworkProtocol {
  let inner: any Clients.EdgeNetworkStub

  /// Creates a new `EdgeNetworkClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.EdgeNetworkStub = try Clients.EdgeNetworkTransport(options)
    inner = Clients.EdgeNetworkRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.EdgeNetworkLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// InitializeZone will initialize resources for a zone in a project.
  ///
  /// @Snippet(path: "EdgeNetwork_InitializeZone")
  public func initializeZone(
    request: InitializeZoneRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.InitializeZoneResponse {
    try await self.inner.initializeZone(request: request, options: options)
  }

  /// Deprecated: not implemented.
  /// Lists Zones in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListZones")
  @available(*, deprecated)
  public func listZones(
    request: ListZonesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListZonesResponse {
    try await self.inner.listZones(request: request, options: options)
  }

  /// Deprecated: not implemented.
  /// Lists Zones in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListZones")
  @available(*, deprecated)
  public func listZones(
    byItem: ListZonesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Zone, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListZonesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listZones(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deprecated: not implemented.
  /// Gets details of a single Zone.
  ///
  /// @Snippet(path: "EdgeNetwork_GetZone")
  @available(*, deprecated)
  public func getZone(
    request: GetZoneRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Zone {
    try await self.inner.getZone(request: request, options: options)
  }

  /// Lists Networks in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListNetworks")
  public func listNetworks(
    request: ListNetworksRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListNetworksResponse {
    try await self.inner.listNetworks(request: request, options: options)
  }

  /// Lists Networks in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListNetworks")
  public func listNetworks(
    byItem: ListNetworksRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Network, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListNetworksResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listNetworks(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Network.
  ///
  /// @Snippet(path: "EdgeNetwork_GetNetwork")
  public func getNetwork(
    request: GetNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Network {
    try await self.inner.getNetwork(request: request, options: options)
  }

  /// Get the diagnostics of a single network resource.
  ///
  /// @Snippet(path: "EdgeNetwork_DiagnoseNetwork")
  public func diagnoseNetwork(
    request: DiagnoseNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse {
    try await self.inner.diagnoseNetwork(request: request, options: options)
  }

  /// Creates a new Network in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateNetwork")
  public func createNetwork(
    request: CreateNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createNetwork(request: request, options: options)
  }

  /// Creates a new Network in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateNetwork")
  public func createNetwork(
    withPolling: CreateNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Network> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Network>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Network(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createNetwork(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Network>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Network.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteNetwork")
  public func deleteNetwork(
    request: DeleteNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteNetwork(request: request, options: options)
  }

  /// Deletes a single Network.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteNetwork")
  public func deleteNetwork(
    withPolling: DeleteNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteNetwork(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists Subnets in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListSubnets")
  public func listSubnets(
    request: ListSubnetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListSubnetsResponse {
    try await self.inner.listSubnets(request: request, options: options)
  }

  /// Lists Subnets in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListSubnets")
  public func listSubnets(
    byItem: ListSubnetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Subnet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListSubnetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSubnets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Subnet.
  ///
  /// @Snippet(path: "EdgeNetwork_GetSubnet")
  public func getSubnet(
    request: GetSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Subnet {
    try await self.inner.getSubnet(request: request, options: options)
  }

  /// Creates a new Subnet in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateSubnet")
  public func createSubnet(
    request: CreateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createSubnet(request: request, options: options)
  }

  /// Creates a new Subnet in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateSubnet")
  public func createSubnet(
    withPolling: CreateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Subnet> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Subnet>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Subnet(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createSubnet(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Subnet>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single Subnet.
  ///
  /// @Snippet(path: "EdgeNetwork_UpdateSubnet")
  public func updateSubnet(
    request: UpdateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateSubnet(request: request, options: options)
  }

  /// Updates the parameters of a single Subnet.
  ///
  /// @Snippet(path: "EdgeNetwork_UpdateSubnet")
  public func updateSubnet(
    withPolling: UpdateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Subnet> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Subnet>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Subnet(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateSubnet(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Subnet>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Subnet.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteSubnet")
  public func deleteSubnet(
    request: DeleteSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteSubnet(request: request, options: options)
  }

  /// Deletes a single Subnet.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteSubnet")
  public func deleteSubnet(
    withPolling: DeleteSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteSubnet(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists Interconnects in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListInterconnects")
  public func listInterconnects(
    request: ListInterconnectsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse {
    try await self.inner.listInterconnects(request: request, options: options)
  }

  /// Lists Interconnects in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListInterconnects")
  public func listInterconnects(
    byItem: ListInterconnectsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Interconnect, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInterconnects(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Interconnect.
  ///
  /// @Snippet(path: "EdgeNetwork_GetInterconnect")
  public func getInterconnect(
    request: GetInterconnectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Interconnect {
    try await self.inner.getInterconnect(request: request, options: options)
  }

  /// Get the diagnostics of a single interconnect resource.
  ///
  /// @Snippet(path: "EdgeNetwork_DiagnoseInterconnect")
  public func diagnoseInterconnect(
    request: DiagnoseInterconnectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse {
    try await self.inner.diagnoseInterconnect(request: request, options: options)
  }

  /// Lists InterconnectAttachments in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListInterconnectAttachments")
  public func listInterconnectAttachments(
    request: ListInterconnectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse {
    try await self.inner.listInterconnectAttachments(request: request, options: options)
  }

  /// Lists InterconnectAttachments in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListInterconnectAttachments")
  public func listInterconnectAttachments(
    byItem: ListInterconnectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInterconnectAttachments(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single InterconnectAttachment.
  ///
  /// @Snippet(path: "EdgeNetwork_GetInterconnectAttachment")
  public func getInterconnectAttachment(
    request: GetInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.InterconnectAttachment {
    try await self.inner.getInterconnectAttachment(request: request, options: options)
  }

  /// Creates a new InterconnectAttachment in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateInterconnectAttachment")
  public func createInterconnectAttachment(
    request: CreateInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createInterconnectAttachment(request: request, options: options)
  }

  /// Creates a new InterconnectAttachment in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateInterconnectAttachment")
  public func createInterconnectAttachment(
    withPolling: CreateInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InterconnectAttachment> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<InterconnectAttachment>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try InterconnectAttachment(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createInterconnectAttachment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<InterconnectAttachment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single InterconnectAttachment.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteInterconnectAttachment")
  public func deleteInterconnectAttachment(
    request: DeleteInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteInterconnectAttachment(request: request, options: options)
  }

  /// Deletes a single InterconnectAttachment.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteInterconnectAttachment")
  public func deleteInterconnectAttachment(
    withPolling: DeleteInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteInterconnectAttachment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists Routers in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListRouters")
  public func listRouters(
    request: ListRoutersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListRoutersResponse {
    try await self.inner.listRouters(request: request, options: options)
  }

  /// Lists Routers in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_ListRouters")
  public func listRouters(
    byItem: ListRoutersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Router, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListRoutersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listRouters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Router.
  ///
  /// @Snippet(path: "EdgeNetwork_GetRouter")
  public func getRouter(
    request: GetRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Router {
    try await self.inner.getRouter(request: request, options: options)
  }

  /// Get the diagnostics of a single router resource.
  ///
  /// @Snippet(path: "EdgeNetwork_DiagnoseRouter")
  public func diagnoseRouter(
    request: DiagnoseRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse {
    try await self.inner.diagnoseRouter(request: request, options: options)
  }

  /// Creates a new Router in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateRouter")
  public func createRouter(
    request: CreateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createRouter(request: request, options: options)
  }

  /// Creates a new Router in a given project and location.
  ///
  /// @Snippet(path: "EdgeNetwork_CreateRouter")
  public func createRouter(
    withPolling: CreateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Router> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Router>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Router(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createRouter(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Router>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single Router.
  ///
  /// @Snippet(path: "EdgeNetwork_UpdateRouter")
  public func updateRouter(
    request: UpdateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateRouter(request: request, options: options)
  }

  /// Updates the parameters of a single Router.
  ///
  /// @Snippet(path: "EdgeNetwork_UpdateRouter")
  public func updateRouter(
    withPolling: UpdateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Router> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Router>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Router(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateRouter(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Router>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Router.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteRouter")
  public func deleteRouter(
    request: DeleteRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteRouter(request: request, options: options)
  }

  /// Deletes a single Router.
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteRouter")
  public func deleteRouter(
    withPolling: DeleteRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteRouter(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "EdgeNetwork_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "EdgeNetwork_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "EdgeNetwork_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeNetwork_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeNetwork_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeNetwork_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeNetwork_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeNetwork_CancelOperation")
  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `EdgeNetworkClient`.
  ///
  /// To mock `EdgeNetworkClient` change your functions to receive
  /// `some EdgeNetworkProtocol` or `any EdgeNetworkProtocol`
  /// and pass a mock implementation in your tests.
  public protocol EdgeNetworkProtocol {
    /// See `EdgeNetworkClient.initializeZone`.
    func initializeZone(request: InitializeZoneRequest) async throws
      -> GoogleCloudEdgenetworkV1.InitializeZoneResponse

    /// See `EdgeNetworkClient.initializeZone`.
    func initializeZone(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.InitializeZoneResponse

    /// See `EdgeNetworkClient.listZones`.
    @available(*, deprecated)
    func listZones(request: ListZonesRequest) async throws
      -> GoogleCloudEdgenetworkV1.ListZonesResponse

    /// See `EdgeNetworkClient.listZones`.
    @available(*, deprecated)
    func listZones(
      byItem: ListZonesRequest
    ) throws -> any AsyncSequence<Zone, Swift.Error>

    /// See `EdgeNetworkClient.listZones`.
    @available(*, deprecated)
    func listZones(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Zone, Swift.Error>

    /// See `EdgeNetworkClient.getZone`.
    @available(*, deprecated)
    func getZone(request: GetZoneRequest) async throws -> GoogleCloudEdgenetworkV1.Zone

    /// See `EdgeNetworkClient.getZone`.
    @available(*, deprecated)
    func getZone(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.Zone

    /// See `EdgeNetworkClient.listNetworks`.
    func listNetworks(request: ListNetworksRequest) async throws
      -> GoogleCloudEdgenetworkV1.ListNetworksResponse

    /// See `EdgeNetworkClient.listNetworks`.
    func listNetworks(
      byItem: ListNetworksRequest
    ) throws -> any AsyncSequence<Network, Swift.Error>

    /// See `EdgeNetworkClient.listNetworks`.
    func listNetworks(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Network, Swift.Error>

    /// See `EdgeNetworkClient.getNetwork`.
    func getNetwork(request: GetNetworkRequest) async throws -> GoogleCloudEdgenetworkV1.Network

    /// See `EdgeNetworkClient.getNetwork`.
    func getNetwork(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.Network

    /// See `EdgeNetworkClient.diagnoseNetwork`.
    func diagnoseNetwork(request: DiagnoseNetworkRequest) async throws
      -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse

    /// See `EdgeNetworkClient.diagnoseNetwork`.
    func diagnoseNetwork(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse

    /// See `EdgeNetworkClient.createNetwork`.
    func createNetwork(request: CreateNetworkRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createNetwork`.
    func createNetwork(withPolling: CreateNetworkRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Network>

    /// See `EdgeNetworkClient.createNetwork`.
    func createNetwork(
      parent: Swift.String,
      network: Network?,
      networkId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Network>

    /// See `EdgeNetworkClient.deleteNetwork`.
    func deleteNetwork(request: DeleteNetworkRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteNetwork`.
    func deleteNetwork(withPolling: DeleteNetworkRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `EdgeNetworkClient.deleteNetwork`.
    func deleteNetwork(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listSubnets`.
    func listSubnets(request: ListSubnetsRequest) async throws
      -> GoogleCloudEdgenetworkV1.ListSubnetsResponse

    /// See `EdgeNetworkClient.listSubnets`.
    func listSubnets(
      byItem: ListSubnetsRequest
    ) throws -> any AsyncSequence<Subnet, Swift.Error>

    /// See `EdgeNetworkClient.listSubnets`.
    func listSubnets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Subnet, Swift.Error>

    /// See `EdgeNetworkClient.getSubnet`.
    func getSubnet(request: GetSubnetRequest) async throws -> GoogleCloudEdgenetworkV1.Subnet

    /// See `EdgeNetworkClient.getSubnet`.
    func getSubnet(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.Subnet

    /// See `EdgeNetworkClient.createSubnet`.
    func createSubnet(request: CreateSubnetRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createSubnet`.
    func createSubnet(withPolling: CreateSubnetRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Subnet>

    /// See `EdgeNetworkClient.createSubnet`.
    func createSubnet(
      parent: Swift.String,
      subnet: Subnet?,
      subnetId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Subnet>

    /// See `EdgeNetworkClient.updateSubnet`.
    func updateSubnet(request: UpdateSubnetRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.updateSubnet`.
    func updateSubnet(withPolling: UpdateSubnetRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Subnet>

    /// See `EdgeNetworkClient.updateSubnet`.
    func updateSubnet(
      subnet: Subnet?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Subnet>

    /// See `EdgeNetworkClient.deleteSubnet`.
    func deleteSubnet(request: DeleteSubnetRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteSubnet`.
    func deleteSubnet(withPolling: DeleteSubnetRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `EdgeNetworkClient.deleteSubnet`.
    func deleteSubnet(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listInterconnects`.
    func listInterconnects(request: ListInterconnectsRequest) async throws
      -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse

    /// See `EdgeNetworkClient.listInterconnects`.
    func listInterconnects(
      byItem: ListInterconnectsRequest
    ) throws -> any AsyncSequence<Interconnect, Swift.Error>

    /// See `EdgeNetworkClient.listInterconnects`.
    func listInterconnects(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Interconnect, Swift.Error>

    /// See `EdgeNetworkClient.getInterconnect`.
    func getInterconnect(request: GetInterconnectRequest) async throws
      -> GoogleCloudEdgenetworkV1.Interconnect

    /// See `EdgeNetworkClient.getInterconnect`.
    func getInterconnect(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.Interconnect

    /// See `EdgeNetworkClient.diagnoseInterconnect`.
    func diagnoseInterconnect(request: DiagnoseInterconnectRequest) async throws
      -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse

    /// See `EdgeNetworkClient.diagnoseInterconnect`.
    func diagnoseInterconnect(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse

    /// See `EdgeNetworkClient.listInterconnectAttachments`.
    func listInterconnectAttachments(request: ListInterconnectAttachmentsRequest) async throws
      -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse

    /// See `EdgeNetworkClient.listInterconnectAttachments`.
    func listInterconnectAttachments(
      byItem: ListInterconnectAttachmentsRequest
    ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error>

    /// See `EdgeNetworkClient.listInterconnectAttachments`.
    func listInterconnectAttachments(
      parent: Swift.String,
    ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error>

    /// See `EdgeNetworkClient.getInterconnectAttachment`.
    func getInterconnectAttachment(request: GetInterconnectAttachmentRequest) async throws
      -> GoogleCloudEdgenetworkV1.InterconnectAttachment

    /// See `EdgeNetworkClient.getInterconnectAttachment`.
    func getInterconnectAttachment(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.InterconnectAttachment

    /// See `EdgeNetworkClient.createInterconnectAttachment`.
    func createInterconnectAttachment(request: CreateInterconnectAttachmentRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createInterconnectAttachment`.
    func createInterconnectAttachment(withPolling: CreateInterconnectAttachmentRequest) async throws
      -> any GoogleCloudGax.PollableOperation<InterconnectAttachment>

    /// See `EdgeNetworkClient.createInterconnectAttachment`.
    func createInterconnectAttachment(
      parent: Swift.String,
      interconnectAttachment: InterconnectAttachment?,
      interconnectAttachmentId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<InterconnectAttachment>

    /// See `EdgeNetworkClient.deleteInterconnectAttachment`.
    func deleteInterconnectAttachment(request: DeleteInterconnectAttachmentRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteInterconnectAttachment`.
    func deleteInterconnectAttachment(withPolling: DeleteInterconnectAttachmentRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.deleteInterconnectAttachment`.
    func deleteInterconnectAttachment(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listRouters`.
    func listRouters(request: ListRoutersRequest) async throws
      -> GoogleCloudEdgenetworkV1.ListRoutersResponse

    /// See `EdgeNetworkClient.listRouters`.
    func listRouters(
      byItem: ListRoutersRequest
    ) throws -> any AsyncSequence<Router, Swift.Error>

    /// See `EdgeNetworkClient.listRouters`.
    func listRouters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Router, Swift.Error>

    /// See `EdgeNetworkClient.getRouter`.
    func getRouter(request: GetRouterRequest) async throws -> GoogleCloudEdgenetworkV1.Router

    /// See `EdgeNetworkClient.getRouter`.
    func getRouter(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.Router

    /// See `EdgeNetworkClient.diagnoseRouter`.
    func diagnoseRouter(request: DiagnoseRouterRequest) async throws
      -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse

    /// See `EdgeNetworkClient.diagnoseRouter`.
    func diagnoseRouter(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse

    /// See `EdgeNetworkClient.createRouter`.
    func createRouter(request: CreateRouterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createRouter`.
    func createRouter(withPolling: CreateRouterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Router>

    /// See `EdgeNetworkClient.createRouter`.
    func createRouter(
      parent: Swift.String,
      router: Router?,
      routerId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Router>

    /// See `EdgeNetworkClient.updateRouter`.
    func updateRouter(request: UpdateRouterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.updateRouter`.
    func updateRouter(withPolling: UpdateRouterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Router>

    /// See `EdgeNetworkClient.updateRouter`.
    func updateRouter(
      router: Router?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Router>

    /// See `EdgeNetworkClient.deleteRouter`.
    func deleteRouter(request: DeleteRouterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteRouter`.
    func deleteRouter(withPolling: DeleteRouterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `EdgeNetworkClient.deleteRouter`.
    func deleteRouter(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `EdgeNetworkClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `EdgeNetworkClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `EdgeNetworkClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `EdgeNetworkClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `EdgeNetworkClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `EdgeNetworkClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `EdgeNetworkClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `EdgeNetworkClient.cancelOperation`.
    func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

    /// See `EdgeNetworkClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `EdgeNetworkClient.initializeZone`.
    func initializeZone(
      request: InitializeZoneRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.InitializeZoneResponse

    /// See `EdgeNetworkClient.listZones`.
    @available(*, deprecated)
    func listZones(
      request: ListZonesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.ListZonesResponse

    /// See `EdgeNetworkClient.listZones`.
    @available(*, deprecated)
    func listZones(
      byItem: ListZonesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Zone, Swift.Error>

    /// See `EdgeNetworkClient.getZone`.
    @available(*, deprecated)
    func getZone(
      request: GetZoneRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.Zone

    /// See `EdgeNetworkClient.listNetworks`.
    func listNetworks(
      request: ListNetworksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.ListNetworksResponse

    /// See `EdgeNetworkClient.listNetworks`.
    func listNetworks(
      byItem: ListNetworksRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Network, Swift.Error>

    /// See `EdgeNetworkClient.getNetwork`.
    func getNetwork(
      request: GetNetworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.Network

    /// See `EdgeNetworkClient.diagnoseNetwork`.
    func diagnoseNetwork(
      request: DiagnoseNetworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse

    /// See `EdgeNetworkClient.createNetwork`.
    func createNetwork(
      request: CreateNetworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createNetwork`.
    func createNetwork(
      withPolling: CreateNetworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Network>

    /// See `EdgeNetworkClient.deleteNetwork`.
    func deleteNetwork(
      request: DeleteNetworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteNetwork`.
    func deleteNetwork(
      withPolling: DeleteNetworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listSubnets`.
    func listSubnets(
      request: ListSubnetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.ListSubnetsResponse

    /// See `EdgeNetworkClient.listSubnets`.
    func listSubnets(
      byItem: ListSubnetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Subnet, Swift.Error>

    /// See `EdgeNetworkClient.getSubnet`.
    func getSubnet(
      request: GetSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.Subnet

    /// See `EdgeNetworkClient.createSubnet`.
    func createSubnet(
      request: CreateSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createSubnet`.
    func createSubnet(
      withPolling: CreateSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Subnet>

    /// See `EdgeNetworkClient.updateSubnet`.
    func updateSubnet(
      request: UpdateSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.updateSubnet`.
    func updateSubnet(
      withPolling: UpdateSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Subnet>

    /// See `EdgeNetworkClient.deleteSubnet`.
    func deleteSubnet(
      request: DeleteSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteSubnet`.
    func deleteSubnet(
      withPolling: DeleteSubnetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listInterconnects`.
    func listInterconnects(
      request: ListInterconnectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse

    /// See `EdgeNetworkClient.listInterconnects`.
    func listInterconnects(
      byItem: ListInterconnectsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Interconnect, Swift.Error>

    /// See `EdgeNetworkClient.getInterconnect`.
    func getInterconnect(
      request: GetInterconnectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.Interconnect

    /// See `EdgeNetworkClient.diagnoseInterconnect`.
    func diagnoseInterconnect(
      request: DiagnoseInterconnectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse

    /// See `EdgeNetworkClient.listInterconnectAttachments`.
    func listInterconnectAttachments(
      request: ListInterconnectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse

    /// See `EdgeNetworkClient.listInterconnectAttachments`.
    func listInterconnectAttachments(
      byItem: ListInterconnectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error>

    /// See `EdgeNetworkClient.getInterconnectAttachment`.
    func getInterconnectAttachment(
      request: GetInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.InterconnectAttachment

    /// See `EdgeNetworkClient.createInterconnectAttachment`.
    func createInterconnectAttachment(
      request: CreateInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createInterconnectAttachment`.
    func createInterconnectAttachment(
      withPolling: CreateInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<InterconnectAttachment>

    /// See `EdgeNetworkClient.deleteInterconnectAttachment`.
    func deleteInterconnectAttachment(
      request: DeleteInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteInterconnectAttachment`.
    func deleteInterconnectAttachment(
      withPolling: DeleteInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listRouters`.
    func listRouters(
      request: ListRoutersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.ListRoutersResponse

    /// See `EdgeNetworkClient.listRouters`.
    func listRouters(
      byItem: ListRoutersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Router, Swift.Error>

    /// See `EdgeNetworkClient.getRouter`.
    func getRouter(
      request: GetRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.Router

    /// See `EdgeNetworkClient.diagnoseRouter`.
    func diagnoseRouter(
      request: DiagnoseRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse

    /// See `EdgeNetworkClient.createRouter`.
    func createRouter(
      request: CreateRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.createRouter`.
    func createRouter(
      withPolling: CreateRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Router>

    /// See `EdgeNetworkClient.updateRouter`.
    func updateRouter(
      request: UpdateRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.updateRouter`.
    func updateRouter(
      withPolling: UpdateRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Router>

    /// See `EdgeNetworkClient.deleteRouter`.
    func deleteRouter(
      request: DeleteRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeNetworkClient.deleteRouter`.
    func deleteRouter(
      withPolling: DeleteRouterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeNetworkClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `EdgeNetworkClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `EdgeNetworkClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `EdgeNetworkClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `EdgeNetworkClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `EdgeNetworkClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `EdgeNetworkClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.EdgeNetworkProtocol {
  public func initializeZone(request: InitializeZoneRequest) async throws
    -> GoogleCloudEdgenetworkV1.InitializeZoneResponse
  {
    try await self.initializeZone(request: request, options: .init())
  }

  public func initializeZone(
    request: InitializeZoneRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.InitializeZoneResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func initializeZone(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.InitializeZoneResponse {
    let request = InitializeZoneRequest().with {
      $0.name = name
    }
    return try await self.initializeZone(request: request)
  }

  public func listZones(request: ListZonesRequest) async throws
    -> GoogleCloudEdgenetworkV1.ListZonesResponse
  {
    try await self.listZones(request: request, options: .init())
  }

  public func listZones(
    request: ListZonesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListZonesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listZones(
    byItem: ListZonesRequest
  ) throws -> any AsyncSequence<Zone, Swift.Error> {
    try self.listZones(byItem: byItem, options: .init())
  }

  public func listZones(
    byItem: ListZonesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Zone, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListZonesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listZones(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Zone, Swift.Error> {
    let request = ListZonesRequest().with {
      $0.parent = parent
    }
    return try self.listZones(byItem: request)
  }

  public func getZone(request: GetZoneRequest) async throws -> GoogleCloudEdgenetworkV1.Zone {
    try await self.getZone(request: request, options: .init())
  }

  public func getZone(
    request: GetZoneRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Zone {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getZone(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.Zone {
    let request = GetZoneRequest().with {
      $0.name = name
    }
    return try await self.getZone(request: request)
  }

  public func listNetworks(request: ListNetworksRequest) async throws
    -> GoogleCloudEdgenetworkV1.ListNetworksResponse
  {
    try await self.listNetworks(request: request, options: .init())
  }

  public func listNetworks(
    request: ListNetworksRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListNetworksResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNetworks(
    byItem: ListNetworksRequest
  ) throws -> any AsyncSequence<Network, Swift.Error> {
    try self.listNetworks(byItem: byItem, options: .init())
  }

  public func listNetworks(
    byItem: ListNetworksRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Network, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListNetworksResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNetworks(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Network, Swift.Error> {
    let request = ListNetworksRequest().with {
      $0.parent = parent
    }
    return try self.listNetworks(byItem: request)
  }

  public func getNetwork(request: GetNetworkRequest) async throws
    -> GoogleCloudEdgenetworkV1.Network
  {
    try await self.getNetwork(request: request, options: .init())
  }

  public func getNetwork(
    request: GetNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Network {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getNetwork(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.Network {
    let request = GetNetworkRequest().with {
      $0.name = name
    }
    return try await self.getNetwork(request: request)
  }

  public func diagnoseNetwork(request: DiagnoseNetworkRequest) async throws
    -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse
  {
    try await self.diagnoseNetwork(request: request, options: .init())
  }

  public func diagnoseNetwork(
    request: DiagnoseNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func diagnoseNetwork(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseNetworkResponse {
    let request = DiagnoseNetworkRequest().with {
      $0.name = name
    }
    return try await self.diagnoseNetwork(request: request)
  }

  public func createNetwork(request: CreateNetworkRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createNetwork(request: request, options: .init())
  }

  public func createNetwork(
    request: CreateNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createNetwork(withPolling: CreateNetworkRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Network>
  {
    try await self.createNetwork(withPolling: withPolling, options: .init())
  }

  public func createNetwork(
    withPolling: CreateNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Network> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Network>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createNetwork(
    parent: Swift.String,
    network: Network?,
    networkId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Network> {
    let request = CreateNetworkRequest().with {
      $0.parent = parent
      $0.network = network
      $0.networkId = networkId
    }
    return try await self.createNetwork(withPolling: request)
  }

  public func deleteNetwork(request: DeleteNetworkRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteNetwork(request: request, options: .init())
  }

  public func deleteNetwork(
    request: DeleteNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteNetwork(withPolling: DeleteNetworkRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteNetwork(withPolling: withPolling, options: .init())
  }

  public func deleteNetwork(
    withPolling: DeleteNetworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteNetwork(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteNetworkRequest().with {
      $0.name = name
    }
    return try await self.deleteNetwork(withPolling: request)
  }

  public func listSubnets(request: ListSubnetsRequest) async throws
    -> GoogleCloudEdgenetworkV1.ListSubnetsResponse
  {
    try await self.listSubnets(request: request, options: .init())
  }

  public func listSubnets(
    request: ListSubnetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListSubnetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSubnets(
    byItem: ListSubnetsRequest
  ) throws -> any AsyncSequence<Subnet, Swift.Error> {
    try self.listSubnets(byItem: byItem, options: .init())
  }

  public func listSubnets(
    byItem: ListSubnetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Subnet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListSubnetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSubnets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Subnet, Swift.Error> {
    let request = ListSubnetsRequest().with {
      $0.parent = parent
    }
    return try self.listSubnets(byItem: request)
  }

  public func getSubnet(request: GetSubnetRequest) async throws -> GoogleCloudEdgenetworkV1.Subnet {
    try await self.getSubnet(request: request, options: .init())
  }

  public func getSubnet(
    request: GetSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Subnet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSubnet(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.Subnet {
    let request = GetSubnetRequest().with {
      $0.name = name
    }
    return try await self.getSubnet(request: request)
  }

  public func createSubnet(request: CreateSubnetRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.createSubnet(request: request, options: .init())
  }

  public func createSubnet(
    request: CreateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSubnet(withPolling: CreateSubnetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Subnet>
  {
    try await self.createSubnet(withPolling: withPolling, options: .init())
  }

  public func createSubnet(
    withPolling: CreateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Subnet> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Subnet>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createSubnet(
    parent: Swift.String,
    subnet: Subnet?,
    subnetId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Subnet> {
    let request = CreateSubnetRequest().with {
      $0.parent = parent
      $0.subnet = subnet
      $0.subnetId = subnetId
    }
    return try await self.createSubnet(withPolling: request)
  }

  public func updateSubnet(request: UpdateSubnetRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.updateSubnet(request: request, options: .init())
  }

  public func updateSubnet(
    request: UpdateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSubnet(withPolling: UpdateSubnetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Subnet>
  {
    try await self.updateSubnet(withPolling: withPolling, options: .init())
  }

  public func updateSubnet(
    withPolling: UpdateSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Subnet> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Subnet>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateSubnet(
    subnet: Subnet?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Subnet> {
    let request = UpdateSubnetRequest().with {
      $0.subnet = subnet
      $0.updateMask = updateMask
    }
    return try await self.updateSubnet(withPolling: request)
  }

  public func deleteSubnet(request: DeleteSubnetRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.deleteSubnet(request: request, options: .init())
  }

  public func deleteSubnet(
    request: DeleteSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSubnet(withPolling: DeleteSubnetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteSubnet(withPolling: withPolling, options: .init())
  }

  public func deleteSubnet(
    withPolling: DeleteSubnetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteSubnet(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteSubnetRequest().with {
      $0.name = name
    }
    return try await self.deleteSubnet(withPolling: request)
  }

  public func listInterconnects(request: ListInterconnectsRequest) async throws
    -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse
  {
    try await self.listInterconnects(request: request, options: .init())
  }

  public func listInterconnects(
    request: ListInterconnectsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInterconnects(
    byItem: ListInterconnectsRequest
  ) throws -> any AsyncSequence<Interconnect, Swift.Error> {
    try self.listInterconnects(byItem: byItem, options: .init())
  }

  public func listInterconnects(
    byItem: ListInterconnectsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Interconnect, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInterconnects(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Interconnect, Swift.Error> {
    let request = ListInterconnectsRequest().with {
      $0.parent = parent
    }
    return try self.listInterconnects(byItem: request)
  }

  public func getInterconnect(request: GetInterconnectRequest) async throws
    -> GoogleCloudEdgenetworkV1.Interconnect
  {
    try await self.getInterconnect(request: request, options: .init())
  }

  public func getInterconnect(
    request: GetInterconnectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Interconnect {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInterconnect(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.Interconnect {
    let request = GetInterconnectRequest().with {
      $0.name = name
    }
    return try await self.getInterconnect(request: request)
  }

  public func diagnoseInterconnect(request: DiagnoseInterconnectRequest) async throws
    -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse
  {
    try await self.diagnoseInterconnect(request: request, options: .init())
  }

  public func diagnoseInterconnect(
    request: DiagnoseInterconnectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func diagnoseInterconnect(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseInterconnectResponse {
    let request = DiagnoseInterconnectRequest().with {
      $0.name = name
    }
    return try await self.diagnoseInterconnect(request: request)
  }

  public func listInterconnectAttachments(request: ListInterconnectAttachmentsRequest) async throws
    -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse
  {
    try await self.listInterconnectAttachments(request: request, options: .init())
  }

  public func listInterconnectAttachments(
    request: ListInterconnectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInterconnectAttachments(
    byItem: ListInterconnectAttachmentsRequest
  ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error> {
    try self.listInterconnectAttachments(byItem: byItem, options: .init())
  }

  public func listInterconnectAttachments(
    byItem: ListInterconnectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudEdgenetworkV1.ListInterconnectAttachmentsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInterconnectAttachments(
    parent: Swift.String,
  ) throws -> any AsyncSequence<InterconnectAttachment, Swift.Error> {
    let request = ListInterconnectAttachmentsRequest().with {
      $0.parent = parent
    }
    return try self.listInterconnectAttachments(byItem: request)
  }

  public func getInterconnectAttachment(request: GetInterconnectAttachmentRequest) async throws
    -> GoogleCloudEdgenetworkV1.InterconnectAttachment
  {
    try await self.getInterconnectAttachment(request: request, options: .init())
  }

  public func getInterconnectAttachment(
    request: GetInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.InterconnectAttachment {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInterconnectAttachment(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.InterconnectAttachment {
    let request = GetInterconnectAttachmentRequest().with {
      $0.name = name
    }
    return try await self.getInterconnectAttachment(request: request)
  }

  public func createInterconnectAttachment(request: CreateInterconnectAttachmentRequest)
    async throws -> GoogleLongrunning.Operation
  {
    try await self.createInterconnectAttachment(request: request, options: .init())
  }

  public func createInterconnectAttachment(
    request: CreateInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createInterconnectAttachment(withPolling: CreateInterconnectAttachmentRequest)
    async throws -> any GoogleCloudGax.PollableOperation<InterconnectAttachment>
  {
    try await self.createInterconnectAttachment(withPolling: withPolling, options: .init())
  }

  public func createInterconnectAttachment(
    withPolling: CreateInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InterconnectAttachment> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<InterconnectAttachment>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInterconnectAttachment(
    parent: Swift.String,
    interconnectAttachment: InterconnectAttachment?,
    interconnectAttachmentId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<InterconnectAttachment> {
    let request = CreateInterconnectAttachmentRequest().with {
      $0.parent = parent
      $0.interconnectAttachment = interconnectAttachment
      $0.interconnectAttachmentId = interconnectAttachmentId
    }
    return try await self.createInterconnectAttachment(withPolling: request)
  }

  public func deleteInterconnectAttachment(request: DeleteInterconnectAttachmentRequest)
    async throws -> GoogleLongrunning.Operation
  {
    try await self.deleteInterconnectAttachment(request: request, options: .init())
  }

  public func deleteInterconnectAttachment(
    request: DeleteInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteInterconnectAttachment(withPolling: DeleteInterconnectAttachmentRequest)
    async throws -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteInterconnectAttachment(withPolling: withPolling, options: .init())
  }

  public func deleteInterconnectAttachment(
    withPolling: DeleteInterconnectAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInterconnectAttachment(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteInterconnectAttachmentRequest().with {
      $0.name = name
    }
    return try await self.deleteInterconnectAttachment(withPolling: request)
  }

  public func listRouters(request: ListRoutersRequest) async throws
    -> GoogleCloudEdgenetworkV1.ListRoutersResponse
  {
    try await self.listRouters(request: request, options: .init())
  }

  public func listRouters(
    request: ListRoutersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.ListRoutersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRouters(
    byItem: ListRoutersRequest
  ) throws -> any AsyncSequence<Router, Swift.Error> {
    try self.listRouters(byItem: byItem, options: .init())
  }

  public func listRouters(
    byItem: ListRoutersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Router, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudEdgenetworkV1.ListRoutersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRouters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Router, Swift.Error> {
    let request = ListRoutersRequest().with {
      $0.parent = parent
    }
    return try self.listRouters(byItem: request)
  }

  public func getRouter(request: GetRouterRequest) async throws -> GoogleCloudEdgenetworkV1.Router {
    try await self.getRouter(request: request, options: .init())
  }

  public func getRouter(
    request: GetRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.Router {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRouter(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.Router {
    let request = GetRouterRequest().with {
      $0.name = name
    }
    return try await self.getRouter(request: request)
  }

  public func diagnoseRouter(request: DiagnoseRouterRequest) async throws
    -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse
  {
    try await self.diagnoseRouter(request: request, options: .init())
  }

  public func diagnoseRouter(
    request: DiagnoseRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func diagnoseRouter(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgenetworkV1.DiagnoseRouterResponse {
    let request = DiagnoseRouterRequest().with {
      $0.name = name
    }
    return try await self.diagnoseRouter(request: request)
  }

  public func createRouter(request: CreateRouterRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.createRouter(request: request, options: .init())
  }

  public func createRouter(
    request: CreateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createRouter(withPolling: CreateRouterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Router>
  {
    try await self.createRouter(withPolling: withPolling, options: .init())
  }

  public func createRouter(
    withPolling: CreateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Router> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Router>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createRouter(
    parent: Swift.String,
    router: Router?,
    routerId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Router> {
    let request = CreateRouterRequest().with {
      $0.parent = parent
      $0.router = router
      $0.routerId = routerId
    }
    return try await self.createRouter(withPolling: request)
  }

  public func updateRouter(request: UpdateRouterRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.updateRouter(request: request, options: .init())
  }

  public func updateRouter(
    request: UpdateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateRouter(withPolling: UpdateRouterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Router>
  {
    try await self.updateRouter(withPolling: withPolling, options: .init())
  }

  public func updateRouter(
    withPolling: UpdateRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Router> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Router>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateRouter(
    router: Router?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Router> {
    let request = UpdateRouterRequest().with {
      $0.router = router
      $0.updateMask = updateMask
    }
    return try await self.updateRouter(withPolling: request)
  }

  public func deleteRouter(request: DeleteRouterRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.deleteRouter(request: request, options: .init())
  }

  public func deleteRouter(
    request: DeleteRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteRouter(withPolling: DeleteRouterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteRouter(withPolling: withPolling, options: .init())
  }

  public func deleteRouter(
    withPolling: DeleteRouterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteRouter(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteRouterRequest().with {
      $0.name = name
    }
    return try await self.deleteRouter(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
