// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing InterconnectAttachment object
public struct InterconnectAttachment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The canonical resource name of the interconnect attachment.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the interconnect attachment was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the interconnect attachment was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. The canonical name of underlying Interconnect object that this
  /// attachment's traffic will traverse through. The name is in the form of
  /// `projects/{project}/locations/{location}/zones/{zone}/interconnects/{interconnect}`.
  public var interconnect: Swift.String = Swift.String()

  /// Optional. The canonical Network name in the form of
  /// `projects/{project}/locations/{location}/zones/{zone}/networks/{network}`.
  public var network: Swift.String = Swift.String()

  /// Required. VLAN id provided by user. Must be site-wise unique.
  public var vlanId: Swift.Int32 = Swift.Int32()

  /// IP (L3) MTU value of the virtual edge cloud.
  /// Valid values are: 1500 and 9000.
  /// Default to 1500 if not set.
  public var mtu: Swift.Int32 = Swift.Int32()

  /// Output only. Current stage of the resource to the device by config push.
  public var state: ResourceState = ResourceState()

  /// Optional. The remote peering network type of the underlying interconnect.
  /// It is required when peering separation is enabled.
  public var peeringType: RemotePeeringNetworkType = RemotePeeringNetworkType()

  /// Initialize a new instance of `InterconnectAttachment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InterconnectAttachment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.InterconnectAttachment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
