// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing Interconnect object
public struct Interconnect: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The canonical resource name of the interconnect.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the subnet was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the subnet was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Optional. Type of interconnect, which takes only the value 'DEDICATED' for
  /// now.
  public var interconnectType: Interconnect.InterconnectType = Interconnect.InterconnectType()

  /// Output only. Unique identifier for the link.
  public var uuid: Swift.String = Swift.String()

  /// Output only. Cloud resource name of the switch device.
  public var deviceCloudResourceName: Swift.String = Swift.String()

  /// Output only. Physical ports (e.g., TenGigE0/0/0/1) that form the
  /// interconnect.
  public var physicalPorts: [Swift.String] = []

  /// Optional. The remote peering network type of the interconnect. It is
  /// required when peering separation is enabled.
  public var remotePeeringNetworkType: RemotePeeringNetworkType = RemotePeeringNetworkType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Interconnect`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Interconnect().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let interconnectType = CodingKeys(stringValue: "interconnectType")
    static let uuid = CodingKeys(stringValue: "uuid")
    static let deviceCloudResourceName = CodingKeys(stringValue: "deviceCloudResourceName")
    static let physicalPorts = CodingKeys(stringValue: "physicalPorts")
    static let remotePeeringNetworkType = CodingKeys(stringValue: "remotePeeringNetworkType")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "interconnectType",
      "uuid",
      "deviceCloudResourceName",
      "physicalPorts",
      "remotePeeringNetworkType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(
      Interconnect.InterconnectType.self, forKey: .interconnectType)
    {
      self.interconnectType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uuid) {
      self.uuid = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .deviceCloudResourceName)
    {
      self.deviceCloudResourceName = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .physicalPorts) {
      self.physicalPorts = value
    }
    if let value = try container.decodeIfPresent(
      RemotePeeringNetworkType.self, forKey: .remotePeeringNetworkType)
    {
      self.remotePeeringNetworkType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.interconnectType, forKey: .interconnectType)
    try container.encode(self.uuid, forKey: .uuid)
    try container.encode(self.deviceCloudResourceName, forKey: .deviceCloudResourceName)
    try container.encode(self.physicalPorts, forKey: .physicalPorts)
    try container.encode(self.remotePeeringNetworkType, forKey: .remotePeeringNetworkType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of interconnect.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum InterconnectType: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Dedicated Interconnect.
    case dedicated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dedicated: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INTERCONNECT_TYPE_UNSPECIFIED"
      case .dedicated: return "DEDICATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InterconnectType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INTERCONNECT_TYPE_UNSPECIFIED": self = .unspecified
      case "DEDICATED": self = .dedicated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InterconnectType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dedicated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INTERCONNECT_TYPE_UNSPECIFIED")
      case .dedicated: return try container.encode("DEDICATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.Interconnect"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
