// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing InterconnectAttachment object
public struct InterconnectAttachment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The canonical resource name of the interconnect attachment.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the interconnect attachment was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the interconnect attachment was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. The canonical name of underlying Interconnect object that this
  /// attachment's traffic will traverse through. The name is in the form of
  /// `projects/{project}/locations/{location}/zones/{zone}/interconnects/{interconnect}`.
  public var interconnect: Swift.String = Swift.String()

  /// Optional. The canonical Network name in the form of
  /// `projects/{project}/locations/{location}/zones/{zone}/networks/{network}`.
  public var network: Swift.String = Swift.String()

  /// Required. VLAN id provided by user. Must be site-wise unique.
  public var vlanId: Swift.Int32 = Swift.Int32()

  /// IP (L3) MTU value of the virtual edge cloud.
  /// Valid values are: 1500 and 9000.
  /// Default to 1500 if not set.
  public var mtu: Swift.Int32 = Swift.Int32()

  /// Output only. Current stage of the resource to the device by config push.
  public var state: ResourceState = ResourceState()

  /// Optional. The remote peering network type of the underlying interconnect.
  /// It is required when peering separation is enabled.
  public var peeringType: RemotePeeringNetworkType = RemotePeeringNetworkType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InterconnectAttachment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InterconnectAttachment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let interconnect = CodingKeys(stringValue: "interconnect")
    static let network = CodingKeys(stringValue: "network")
    static let vlanId = CodingKeys(stringValue: "vlanId")
    static let mtu = CodingKeys(stringValue: "mtu")
    static let state = CodingKeys(stringValue: "state")
    static let peeringType = CodingKeys(stringValue: "peeringType")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "interconnect",
      "network",
      "vlanId",
      "mtu",
      "state",
      "peeringType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .interconnect) {
      self.interconnect = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .vlanId) {
      self.vlanId = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .mtu) {
      self.mtu = value
    }
    if let value = try container.decodeIfPresent(ResourceState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(
      RemotePeeringNetworkType.self, forKey: .peeringType)
    {
      self.peeringType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.interconnect, forKey: .interconnect)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.vlanId, forKey: .vlanId)
    try container.encode(self.mtu, forKey: .mtu)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.peeringType, forKey: .peeringType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.InterconnectAttachment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
