// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing Network object
public struct Network: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The canonical resource name of the network.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the network was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the network was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// IP (L3) MTU value of the network.
  /// Valid values are: 1500 and 9000.
  /// Default to 1500 if not set.
  public var mtu: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `Network`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Network().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.Network"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
