// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing Router object
public struct Router: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The canonical resource name of the router.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the router was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the router was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. The canonical name of the network to which this router belongs.
  /// The name is in the form of
  /// `projects/{project}/locations/{location}/zones/{zone}/networks/{network}`.
  public var network: Swift.String = Swift.String()

  /// Router interfaces.
  public var interface: [Router.Interface] = []

  /// BGP peers.
  public var bgpPeer: [Router.BgpPeer] = []

  /// BGP information specific to this router.
  public var bgp: Router.Bgp? = nil

  /// Output only. Current stage of the resource to the device by config push.
  public var state: ResourceState = ResourceState()

  /// Optional. A list of CIDRs in IP/Length format to advertise northbound as
  /// static routes from this router.
  public var routeAdvertisements: [Swift.String] = []

  /// Initialize a new instance of `Router`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Router().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Router Interface defines the GDCE zone side layer-3 information for
  /// building the BGP session.
  public struct Interface: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of this interface entry. Unique within the Zones resource.
    public var name: Swift.String = Swift.String()

    /// IP address and range of the interface.
    public var ipv4Cidr: Swift.String = Swift.String()

    /// IPv6 address and range of the interface.
    public var ipv6Cidr: Swift.String = Swift.String()

    /// The canonical name of the linked Interconnect attachment.
    public var linkedInterconnectAttachment: Swift.String = Swift.String()

    /// The canonical name of the subnetwork resource that this interface
    /// belongs to.
    public var subnetwork: Swift.String = Swift.String()

    /// Create loopback interface in the router when specified.
    /// The number of IP addresses must match the number of TOR devices.
    public var loopbackIpAddresses: [Swift.String] = []

    /// Initialize a new instance of `Interface`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Interface().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgenetwork.v1.Router.Interface"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// BGPPeer defines the peer side layer-3 information for building the BGP
  /// session.
  public struct BgpPeer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of this BGP peer. Unique within the Zones resource.
    public var name: Swift.String = Swift.String()

    /// Name of the RouterInterface the BGP peer is associated with.
    public var interface: Swift.String = Swift.String()

    /// IP range of the interface within Google.
    public var interfaceIpv4Cidr: Swift.String = Swift.String()

    /// IPv6 range of the interface within Google.
    public var interfaceIpv6Cidr: Swift.String = Swift.String()

    /// IP range of the BGP interface outside Google.
    public var peerIpv4Cidr: Swift.String = Swift.String()

    /// IPv6 range of the BGP interface outside Google.
    public var peerIpv6Cidr: Swift.String = Swift.String()

    /// Peer BGP Autonomous System Number (ASN). Each BGP interface may use
    /// a different value.
    public var peerAsn: Swift.UInt32 = Swift.UInt32()

    /// Output only. Local BGP Autonomous System Number (ASN).
    /// This field is ST_NOT_REQUIRED because it stores private ASNs, which are
    /// meaningless outside the zone in which they are being used.
    public var localAsn: Swift.UInt32 = Swift.UInt32()

    /// Initialize a new instance of `BgpPeer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BgpPeer().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgenetwork.v1.Router.BgpPeer"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// BGP information specific to this router.
  public struct Bgp: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Locally assigned BGP ASN.
    public var asn: Swift.UInt32 = Swift.UInt32()

    /// The interval in seconds between BGP keepalive messages that are
    /// sent to the peer. Default is 20 with value between 20 and 60.
    public var keepaliveIntervalInSeconds: Swift.UInt32 = Swift.UInt32()

    /// Initialize a new instance of `Bgp`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Bgp().with { $0.asn = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgenetwork.v1.Router.Bgp"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.Router"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
