// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describing the current status of a router.
public struct RouterStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The canonical name of the network to which this router belongs.
  public var network: Swift.String = Swift.String()

  /// A list of BgpPeerStatus objects, describing all BGP peers related to this
  /// router.
  public var bgpPeerStatus: [RouterStatus.BgpPeerStatus] = []

  /// Initialize a new instance of `RouterStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RouterStatus().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Status of a BGP peer.
  public struct BgpPeerStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of this BGP peer. Unique within the Routers resource.
    public var name: Swift.String = Swift.String()

    /// IP address of the local BGP interface.
    public var ipAddress: Swift.String = Swift.String()

    /// IP address of the remote BGP interface.
    public var peerIpAddress: Swift.String = Swift.String()

    /// The current status of BGP.
    public var status: RouterStatus.BgpPeerStatus.BgpStatus = RouterStatus.BgpPeerStatus.BgpStatus()

    /// BGP state as specified in RFC1771.
    public var state: Swift.String = Swift.String()

    /// Time this session has been up.
    /// Format:
    ///  14 years, 51 weeks, 6 days, 23 hours, 59 minutes, 59 seconds
    public var uptime: Swift.String = Swift.String()

    /// Time this session has been up, in seconds.
    public var uptimeSeconds: Swift.Int64 = Swift.Int64()

    /// A collection of counts for prefixes.
    public var prefixCounter: RouterStatus.PrefixCounter? = nil

    /// Initialize a new instance of `BgpPeerStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BgpPeerStatus().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Status of the BGP peer: {UP, DOWN}
    public enum BgpStatus: Codable, Equatable, Sendable {
      /// The default status indicating BGP session is in unknown state.
      case unknown
      /// The UP status indicating BGP session is established.
      case up
      /// The DOWN state indicating BGP session is not established yet.
      case down
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unknown
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unknown: return 0
        case .up: return 1
        case .down: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unknown: return "UNKNOWN"
        case .up: return "UP"
        case .down: return "DOWN"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "UNKNOWN": self = .unknown
        case "UP": self = .up
        case "DOWN": self = .down
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unknown
        case 1: self = .up
        case 2: self = .down
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unknown: return try container.encode(0)
        case .up: return try container.encode(1)
        case .down: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgenetwork.v1.RouterStatus.BgpPeerStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// PrefixCounter contains a collection of prefixes related counts.
  public struct PrefixCounter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Number of prefixes advertised.
    public var advertised: Swift.Int64 = Swift.Int64()

    /// Number of prefixes denied.
    public var denied: Swift.Int64 = Swift.Int64()

    /// Number of prefixes received.
    public var received: Swift.Int64 = Swift.Int64()

    /// Number of prefixes sent.
    public var sent: Swift.Int64 = Swift.Int64()

    /// Number of prefixes suppressed.
    public var suppressed: Swift.Int64 = Swift.Int64()

    /// Number of prefixes withdrawn.
    public var withdrawn: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `PrefixCounter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrefixCounter().with { $0.advertised = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgenetwork.v1.RouterStatus.PrefixCounter"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.RouterStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
