// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing Subnet object
public struct Subnet: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The canonical resource name of the subnet.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the subnet was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the subnet was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. The network that this subnetwork belongs to.
  public var network: Swift.String = Swift.String()

  /// The ranges of ipv4 addresses that are owned by this subnetwork.
  public var ipv4Cidr: [Swift.String] = []

  /// The ranges of ipv6 addresses that are owned by this subnetwork.
  public var ipv6Cidr: [Swift.String] = []

  /// Optional. VLAN id provided by user. If not specified we assign one
  /// automatically.
  public var vlanId: Swift.Int32 = Swift.Int32()

  /// Optional. A bonding type in the subnet creation specifies whether a VLAN
  /// being created will be present on Bonded or Non-Bonded or Both port types.
  /// In addition, this flag is to be used to set the specific network
  /// configuration which clusters can then use for their workloads based on the
  /// bonding choice.
  public var bondingType: Subnet.BondingType = Subnet.BondingType()

  /// Output only. Current stage of the resource to the device by config push.
  public var state: ResourceState = ResourceState()

  /// Initialize a new instance of `Subnet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Subnet().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Bonding type in the subnet.
  public enum BondingType: Codable, Equatable, Sendable {
    /// Unspecified
    /// Bonding type will be unspecified by default and if the user chooses to
    /// not specify a bonding type at time of creating the VLAN. This will be
    /// treated as mixed bonding where the VLAN will have both bonded and
    /// non-bonded connectivity to machines.
    case unspecified
    /// Multi homed.
    case bonded
    /// Single homed.
    case nonBonded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .bonded: return 1
      case .nonBonded: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BONDING_TYPE_UNSPECIFIED"
      case .bonded: return "BONDED"
      case .nonBonded: return "NON_BONDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BondingType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BONDING_TYPE_UNSPECIFIED": self = .unspecified
      case "BONDED": self = .bonded
      case "NON_BONDED": self = .nonBonded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BondingType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .bonded
      case 2: self = .nonBonded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .bonded: return try container.encode(1)
      case .nonBonded: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.Subnet"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
