// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Google Edge Cloud zone.
public struct Zone: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the zone.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the zone was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the zone was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Deprecated: not implemented.
  /// Labels as key value pairs.
  @available(*, deprecated)
  public var labels: [Swift.String: Swift.String] = [:]

  /// Deprecated: not implemented.
  /// The deployment layout type.
  @available(*, deprecated)
  public var layoutName: Swift.String = Swift.String()

  /// Initialize a new instance of `Zone`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Zone().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgenetwork.v1.Zone"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
